/* Auto-generated by scripts/generate-build-info.mjs — do not edit. */
export const BUILD_SHA: string | null = "192c8887bdcfac5fbd49b5f1e56093dbac48ca3e";
export const BUILD_TIME: string | null = "2026-09-03T19:57:11.389Z";
