/* Auto-generated by scripts/generate-build-info.mjs — do not edit. */
export const BUILD_VERSION: string | null = "2.1.0";
export const BUILD_SHA: string | null = "2eb4f1d68080223e60d7bbbccee4a7df0f48611e";
export const BUILD_TIME: string | null = "2026-09-04T11:33:04.501Z";
