/* Auto-generated by scripts/generate-build-info.mjs — do not edit. */
export const BUILD_SHA: string | null = "614ebbd57e01f98ea0e0fc62cd2b54b1f86b2dac";
export const BUILD_TIME: string | null = "2026-07-13T09:18:03.285Z";
